# Generated by Django 3.2.13 on 2023-05-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230508_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='func',
            name='library',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='func',
            name='type_return',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
    ]
